version: "3.9"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    environment:
      - node.name=elasticsearch-demo
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - elasticstack-network
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.1.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elasticstack-network
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

volumes:
  elasticsearch-data:

networks:
  elasticstack-network:
    driver: bridge